config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'home#index'

  constraints subdomain: /blog/ do
    # namespace :blog, :path => '/' do
    #   get '/', to: 'home#index', as: :root
    #   resources :home, only: :index
    #   namespace :posts do
    #     resources :prayer_requests, only: [:index, :show]
    #     resources :drama_team, only: [:index, :show]
    #     resources :korean_ministry, only: [:index, :show]
    #     resources :devotion, only: [:index, :show]
    #     resources :family, only: [:index, :show]
    #     resources :daily_life, only: [:index, :show]
    #     resources :tags, only: [:create, :show]
    #   end
    # end
  end

  constraints subdomain: // do
    get '/', to: 'blog/home#index', as: :root
    resources :home
    namespace :admin do
      resources :dashboard, only: :index
      namespace :blog do
        resources :posts do
          post :posting, on: :member
          post :undo, on: :member
        end
      end
    end
    namespace :blog do
      resources :home, only: :index
      namespace :posts do
        resources :prayer_requests, only: %i[index show]
        resources :drama_team, only: %i[index show]
        resources :korean_ministry, only: %i[index show]
        resources :devotion, only: %i[index show]
        resources :family, only: %i[index show]
        resources :daily_life, only: %i[index show]
        resources :tags, only: %i[create show]
        resources :thoughts, only: %i[index show]
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :blog do
      resources :home, only: :index
      resources :posts, only: %i[index show] do
        get :tags_index, on: :collection
        resources :image_sort do
          put :sort, on: :member
        end
      end
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  category   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  include AASM
  acts_as_taggable

  belongs_to :main_image, class_name: "PostImage", foreign_key: "main_image_id", optional: true
  has_many :images, -> { order(position: :asc) }, class_name: "PostImage", foreign_key: "post_id", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  scope :on_posting, -> { where(aasm_state: :posting).order(id: :desc)}
  scope :latest, -> { on_posting.limit(4) }
  scope :category_on, ->(category) { on_posting.where(category: category) }

  enum category: { prayer_requests: 0, drama_team: 1, korean_ministry: 2, devotion: 3, family: 4, daily_life: 5, thoughts: 6 }

  aasm do
    state :draft, initial: true
    state :posting

    event :posting do
      transitions from: [:draft], to: :posting
    end

    event :undo do
      transitions from: [:posting], to: :draft
    end
  end

  class << self
    def posts_count(category)
      Post.category_on(category).on_posting.count
    end

    def popular_tags
      Post.tag_counts.order(taggings_count: :desc).limit(10)
    end
  end

  def images_build
    images.build
  end

  def refined_date
    created_at.strftime("%b %d, %Y")
  end

  def remove_images(ids)
    self.images.find(ids).map{ |img| img.destroy! }
  end

  def main_image_url
    main_image.present? ? main_image.image_url : ""
  end

  def truncate_body(max=500)
    self.body.length > max ? "#{self.body[0...max]}..." : self.body
  end

  def truncate_title(max=25)
    self.title.length > max ? "#{self.title[0...max]}..." : self.title
  end
end

app/controllers/admin/blog/posts_controller.rb
class Admin::Blog::PostsController < Admin::BaseController
  before_action :setup_post, except: [:index, :new, :create]

  def index
    @posts = Post.order(id: :desc)
  end

  def show; end

  def new
    @post = Post.new
    @post.images_build
  end

  def create
    @post = Post.new post_params.merge(tag_list: params[:post][:tag_list].gsub("#", ","))
    if @post.save
      redirect_to admin_blog_posts_path, notice: I18n.t('views.common.created', model: Post.model_name.human)
    else
      render :new, alert: I18n.t('views.common.crud_error')
      @post.images_build
    end
  end

  def edit
    # @post.images_build
  end

  def update
    ActiveRecord::Base.transaction do
      @post.update!(post_params.merge(tag_list: params[:post][:tag_list].gsub("#", ",")))
      @post.update!(update_params) if params[:update_post].present?
      @post.remove_images(params[:remove_img_id]) if params[:remove_img_id]
    end
    redirect_to admin_blog_posts_path, notice: I18n.t('views.common.updated', model: Post.model_name.human)
  rescue => e
    redirect_to edit_admin_blog_post_path(@post), alert: e.to_s
  end

  def destroy
    @post.destroy
    redirect_to admin_blog_posts_path, notice: I18n.t('views.common.deleted', model: Post.model_name.human)
  end

  def posting
    return render :show, alert: I18n.t('views.posts.main_image_required') if params[:main_image_id].blank?
    main_image = @post.images.find(params[:main_image_id])
    @post.main_image = main_image
    @post.posting! if @post.may_posting?
    redirect_to admin_blog_posts_path, notice: I18n.t('views.posts.posted')
  end

  def undo
    @post.undo! if @post.may_undo?
    redirect_to admin_blog_posts_path, notice: I18n.t('views.posts.cancel')
  end

  private

  def setup_post
    @post = Post.find params[:id]
  end

  def update_params
    params.require(:update_post).permit(
      images_attributes: [:id, :image]
    )
  end

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :category,
      images_attributes: [:id, :image, :_destroy]
    )
  end
end

app/controllers/api/blog/home_controller.rb
class Api::Blog::HomeController < ActionController::API
  def index
    @q = Post.on_posting.ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(10)
    prev_page = @posts.prev_page.nil? ? 0 : @posts.prev_page
    next_page = @posts.next_page.nil? ? 0 : @posts.next_page
    pages_info = {
      current_page: @posts.current_page,
      total_pages: @posts.total_pages,
      next_page: next_page,
      prev_page: prev_page
    }
    render json: @posts, adapter: :json, meta: {pages_info: pages_info}, status: :ok
  end
end

app/controllers/api/blog/image_sort_controller.rb
class Api::Blog::ImageSortController < ActionController::API
  def index
    post = Post.find params[:post_id]
    @images = post.images
    render json: @images, status: :ok
  end

  def sort
    post = Post.find params[:post_id]
    image = post.images.find params[:id]
    image.insert_at params[:new_index]
    post.reload
    @images = post.images
    render json: @images, status: :ok
  end
end

app/controllers/api/blog/posts_controller.rb
class Api::Blog::PostsController < ActionController::API
  def index
    @q = Post.category_on(params[:category]).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(5)
    render json: @posts, adapter: :json, meta: { pages_info: pages_info }, status: :ok
  end

  def show
    @post = Post.find params[:id]
    render json: @post, status: :ok
  end

  def tags_index
    @posts = Post.on_posting.tagged_with(params[:tag_name]).page(params[:page]).per(5)
    render json: @posts, adapter: :json, meta: { pages_info: pages_info }, status: :ok
  end

  private

  def pages_info
    prev_page = @posts.prev_page.nil? ? 0 : @posts.prev_page
    next_page = @posts.next_page.nil? ? 0 : @posts.next_page
    { current_page: @posts.current_page,
      total_pages: @posts.total_pages,
      next_page: next_page,
      prev_page: prev_page }
  end
end

app/controllers/blog/base_controller.rb
class Blog::BaseController < ApplicationController
  before_action :subdomain_name
  before_action :header_name
  before_action :footer_name

  def subdomain_name
    @subdomain_name = :blog
  end

  def header_name
    @header_name = "common/partials/blog_header"
  end

  def footer_name
    @footer_name = "common/partials/blog_footer"
  end

  def page_name(name)
    @page_name = name
  end

  protected

  def setup_post(category)
    @post = Post.category_on(category).find params[:id]
  end
end

app/controllers/blog/home_controller.rb
class Blog::HomeController < Blog::BaseController
  def index; end
end

app/controllers/blog/posts/daily_life_controller.rb
class Blog::Posts::DailyLifeController < Blog::BaseController
  before_action :setup_post, except: [:index]

  def index
    @category = :daily_life
  end

  def show; end

  private

  def setup_post
    @post = Post.find params[:id]
  end
end

app/controllers/blog/posts/devotion_controller.rb
class Blog::Posts::DevotionController < Blog::BaseController
  before_action -> { setup_post(:devotion) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :devotion
  end

  def show; end
end

app/controllers/blog/posts/drama_team_controller.rb
class Blog::Posts::DramaTeamController < Blog::BaseController
  before_action -> { setup_post(:drama_team) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :drama_team
  end

  def show; end
end

app/controllers/blog/posts/family_controller.rb
class Blog::Posts::FamilyController < Blog::BaseController
  before_action -> { setup_post(:family) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :family
  end

  def show; end
end

app/controllers/blog/posts/korean_ministry_controller.rb
class Blog::Posts::KoreanMinistryController < Blog::BaseController
  before_action -> { setup_post(:korean_ministry) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :korean_ministry
  end

  def show; end
end

app/controllers/blog/posts/prayer_requests_controller.rb
class Blog::Posts::PrayerRequestsController < Blog::BaseController
  before_action -> { setup_post(:prayer_requests) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :prayer_requests
  end

  def show; end
end

app/controllers/blog/posts/tags_controller.rb
class Blog::Posts::TagsController < Blog::BaseController
  def create
    redirect_to blog_posts_tag_path(params[:tag_name])
  end

  def show
    @tag_name = params[:id]
  end
end

app/controllers/blog/posts/thoughts_controller.rb
class Blog::Posts::DailyLifeController < Blog::BaseController
  before_action -> { setup_post(:thoughts) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :thoughts
  end

  def show; end
end

app/helpers/admin/blog/posts_helper.rb
module Admin::Blog::PostsHelper
  def refined_tag_list(post)
    post.tag_list.present? ? post.tag_list.map { |tag| "##{tag}" }.to_s.delete("\"|,|[|]") : ""
  end
end

app/views/admin/blog/posts/_form.html.slim
.form-group
  = f.label :title
  = f.text_field :title, class: "form-control", placeholder: t('views.posts.placeholder.title')
.form-group
  = f.label :body
  = f.text_area :body, class: "form-control", rows: 20, placeholder: t('views.posts.placeholder.body')
.form-group
  = f.label :category
  = f.select :category, Post.categories_i18n.invert, {prompt: t('helpers.select.prompt')}, {class: "form-control"}
.form-group
  label
    = f.label :images
  .clearfix
  - post.images.each do |image|
    .col-sm-6.col-md-3.col-lg-3
      = f.fields_for :images, image do |im|
        - if image.persisted? && image.image?
          - if image == post.main_image
            - main_image = "main-image"
          .remove_images_area.float-left
            input type="checkbox" name="remove_img_id[]" value="#{image.id}" id="remove_images_#{image.id}"
            label for="remove_images_#{image.id}"
              = image_tag image.thumb_url, class: "img-fluid d-block float-left margin-right-10 #{main_image}"
          - next
                / = link_to remove_image_screeners_survey_path(current_resource, survey), method: :delete, class: "btn btn-sm btn-success", data: { confirm: t('views.common.confirm'), toggle:"tooltip" }, title: t('views.common.btn.delete') do
                /   i.fa.fa-close
        - else
          .margin-top-10
            = im.file_field :image, multiple: true, name: "post[images_attributes][][image]"
  .clearfix
  - if post.images.present? && post.images.first.persisted?
    = f.file_field :update_new_image, multiple: true, name: "update_post[images_attributes][][image]"
.form-group
  = f.label :tag_list
  = f.text_field :tag_list, value: refined_tag_list(post), class: "form-control"
/ .form-group
/   = f.label :images
/   = f.file_field :images, multiple: true

app/views/admin/blog/posts/edit.html.slim
= form_for @post, url: admin_blog_post_path(@post) do |f|
  = render 'common/error_object', object: @post
  = render 'admin/blog/posts/form', f: f, post: @post
  .form-actions
    = f.submit t('views.posts.update'), class: "btn btn-border-d btn-round", data: { disable_with: t('views.common.sending') }

app/views/admin/blog/posts/index.html.slim
h1 Post Index
= link_to t('views.common.navigator.dashboard'), admin_dashboard_index_path, class: "btn btn-primary margin-right-10"
= link_to t('views.common.new_obj', model: Post.model_name.human), new_admin_blog_post_path, class: "btn btn-border-d btn-round"
table.table
  thead
    tr
      th = t('views.posts.id')
      th = t('views.posts.title')
      th = t('views.posts.body')
      th = t('views.posts.category')
      th = t('views.posts.status')
      th
  tbody
    - @posts.each do |post|
      tr
        td = post.id
        td
          = link_to post.title, admin_blog_post_path(post)
        td = truncate post.body, length: 30
        td = post.category
        td = post.aasm.human_state
        td
          = link_to edit_admin_blog_post_path(post), class: "btn btn-primary btn-icon-jo margin-right-10" do
            i.fa.fa-edit
          = link_to admin_blog_post_path(post), method: :delete, class: "btn btn-danger btn-icon-jo margin-right-10", data: { confirm: t('views.common.confirm') } do
            i.fa.fa-trash-o

app/views/admin/blog/posts/new.html.slim
= form_for @post, url: admin_blog_posts_path do |f|
  = render 'common/error_object', object: @post
  = render 'admin/blog/posts/form', f: f, post: @post
  .form-actions
    = f.submit t('views.posts.submit'), class: "btn btn-border-d btn-round", data: { disable_with: t('views.common.sending') }

app/views/admin/blog/posts/show.html.slim
p = @post.title
p = @post.body
p = @post.category
p = refined_tag_list(@post)
- if @post.draft?
  = form_tag posting_admin_blog_post_path(@post.id) do
    - @post.images.each do |img|
      .select_main_image.float-left
        = radio_button_tag 'main_image_id', img.id
        = label_tag "main_image_id_#{img.id}" do
          = image_tag img.thumb_url
    .clearfix
    .form-actions
      = submit_tag t('views.posts.posting'), class: "btn btn-border-d btn-round"
- else
  #post-img
    image-sortable post-id="#{@post.id}"
  .clearfix
  = link_to t('views.posts.undo'), undo_admin_blog_post_path(@post), class: "btn btn-border-d btn-round", method: :post

= render 'components/admin/posts/image_sortable'
= javascript_pack_tag 'image_sortable'