config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'home#index'

  constraints subdomain: /blog/ do
    # namespace :blog, :path => '/' do
    #   get '/', to: 'home#index', as: :root
    #   resources :home, only: :index
    #   namespace :posts do
    #     resources :prayer_requests, only: [:index, :show]
    #     resources :drama_team, only: [:index, :show]
    #     resources :korean_ministry, only: [:index, :show]
    #     resources :devotion, only: [:index, :show]
    #     resources :family, only: [:index, :show]
    #     resources :daily_life, only: [:index, :show]
    #     resources :tags, only: [:create, :show]
    #   end
    # end
  end

  constraints subdomain: // do
    get '/', to: 'blog/home#index', as: :root
    resources :home
    namespace :admin do
      resources :dashboard, only: :index
      namespace :blog do
        resources :posts do
          post :posting, on: :member
          post :undo, on: :member
        end
      end
    end
    namespace :blog do
      resources :home, only: :index
      namespace :posts do
        resources :prayer_requests, only: %i[index show]
        resources :drama_team, only: %i[index show]
        resources :korean_ministry, only: %i[index show]
        resources :devotion, only: %i[index show]
        resources :family, only: %i[index show]
        resources :daily_life, only: %i[index show]
        resources :tags, only: %i[create show]
        resources :thoughts, only: %i[index show]
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :blog do
      resources :home, only: :index
      resources :posts, only: %i[index show] do
        get :tags_index, on: :collection
        resources :image_sort do
          put :sort, on: :member
        end
      end
    end
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  category   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  include AASM
  acts_as_taggable

  belongs_to :main_image, class_name: "PostImage", foreign_key: "main_image_id", optional: true
  has_many :images, -> { order(position: :asc) }, class_name: "PostImage", foreign_key: "post_id", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  scope :on_posting, -> { where(aasm_state: :posting).order(id: :desc)}
  scope :latest, -> { on_posting.limit(4) }
  scope :category_on, ->(category) { on_posting.where(category: category) }

  enum category: { prayer_requests: 0, drama_team: 1, korean_ministry: 2, devotion: 3, family: 4, daily_life: 5, thoughts: 6 }

  aasm do
    state :draft, initial: true
    state :posting

    event :posting do
      transitions from: [:draft], to: :posting
    end

    event :undo do
      transitions from: [:posting], to: :draft
    end
  end

  class << self
    def posts_count(category)
      Post.category_on(category).on_posting.count
    end

    def popular_tags
      Post.tag_counts.order(taggings_count: :desc).limit(10)
    end
  end

  def images_build
    images.build
  end

  def refined_date
    created_at.strftime("%b %d, %Y")
  end

  def remove_images(ids)
    self.images.find(ids).map{ |img| img.destroy! }
  end

  def main_image_url
    main_image.present? ? main_image.image_url : ""
  end

  def truncate_body(max=500)
    self.body.length > max ? "#{self.body[0...max]}..." : self.body
  end

  def truncate_title(max=25)
    self.title.length > max ? "#{self.title[0...max]}..." : self.title
  end
end

app/controllers/admin/blog/posts_controller.rb
class Admin::Blog::PostsController < Admin::BaseController
  before_action :setup_post, except: [:index, :new, :create]

  def index
    @posts = Post.order(id: :desc)
  end

  def show; end

  def new
    @post = Post.new
    @post.images_build
  end

  def create
    @post = Post.new post_params.merge(tag_list: params[:post][:tag_list].gsub("#", ","))
    if @post.save
      redirect_to admin_blog_posts_path, notice: I18n.t('views.common.created', model: Post.model_name.human)
    else
      render :new, alert: I18n.t('views.common.crud_error')
      @post.images_build
    end
  end

  def edit
    # @post.images_build
  end

  def update
    ActiveRecord::Base.transaction do
      @post.update!(post_params.merge(tag_list: params[:post][:tag_list].gsub("#", ",")))
      @post.update!(update_params) if params[:update_post].present?
      @post.remove_images(params[:remove_img_id]) if params[:remove_img_id]
    end
    redirect_to admin_blog_posts_path, notice: I18n.t('views.common.updated', model: Post.model_name.human)
  rescue => e
    redirect_to edit_admin_blog_post_path(@post), alert: e.to_s
  end

  def destroy
    @post.destroy
    redirect_to admin_blog_posts_path, notice: I18n.t('views.common.deleted', model: Post.model_name.human)
  end

  def posting
    return render :show, alert: I18n.t('views.posts.main_image_required') if params[:main_image_id].blank?
    main_image = @post.images.find(params[:main_image_id])
    @post.main_image = main_image
    @post.posting! if @post.may_posting?
    redirect_to admin_blog_posts_path, notice: I18n.t('views.posts.posted')
  end

  def undo
    @post.undo! if @post.may_undo?
    redirect_to admin_blog_posts_path, notice: I18n.t('views.posts.cancel')
  end

  private

  def setup_post
    @post = Post.find params[:id]
  end

  def update_params
    params.require(:update_post).permit(
      images_attributes: [:id, :image]
    )
  end

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :category,
      images_attributes: [:id, :image, :_destroy]
    )
  end
end

app/controllers/api/blog/posts_controller.rb
class Api::Blog::PostsController < ActionController::API
  def index
    @q = Post.category_on(params[:category]).ransack(params[:q])
    @posts = @q.result.page(params[:page]).per(5)
    render json: @posts, adapter: :json, meta: { pages_info: pages_info }, status: :ok
  end

  def show
    @post = Post.find params[:id]
    render json: @post, status: :ok
  end

  def tags_index
    @posts = Post.on_posting.tagged_with(params[:tag_name]).page(params[:page]).per(5)
    render json: @posts, adapter: :json, meta: { pages_info: pages_info }, status: :ok
  end

  private

  def pages_info
    prev_page = @posts.prev_page.nil? ? 0 : @posts.prev_page
    next_page = @posts.next_page.nil? ? 0 : @posts.next_page
    { current_page: @posts.current_page,
      total_pages: @posts.total_pages,
      next_page: next_page,
      prev_page: prev_page }
  end
end

app/controllers/blog/posts/daily_life_controller.rb
class Blog::Posts::DailyLifeController < Blog::BaseController
  before_action :setup_post, except: [:index]

  def index
    @category = :daily_life
  end

  def show; end

  private

  def setup_post
    @post = Post.find params[:id]
  end
end

app/controllers/blog/posts/devotion_controller.rb
class Blog::Posts::DevotionController < Blog::BaseController
  before_action -> { setup_post(:devotion) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :devotion
  end

  def show; end
end

app/controllers/blog/posts/drama_team_controller.rb
class Blog::Posts::DramaTeamController < Blog::BaseController
  before_action -> { setup_post(:drama_team) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :drama_team
  end

  def show; end
end

app/controllers/blog/posts/family_controller.rb
class Blog::Posts::FamilyController < Blog::BaseController
  before_action -> { setup_post(:family) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :family
  end

  def show; end
end

app/controllers/blog/posts/korean_ministry_controller.rb
class Blog::Posts::KoreanMinistryController < Blog::BaseController
  before_action -> { setup_post(:korean_ministry) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :korean_ministry
  end

  def show; end
end

app/controllers/blog/posts/prayer_requests_controller.rb
class Blog::Posts::PrayerRequestsController < Blog::BaseController
  before_action -> { setup_post(:prayer_requests) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :prayer_requests
  end

  def show; end
end

app/controllers/blog/posts/tags_controller.rb
class Blog::Posts::TagsController < Blog::BaseController
  def create
    redirect_to blog_posts_tag_path(params[:tag_name])
  end

  def show
    @tag_name = params[:id]
  end
end

app/controllers/blog/posts/thoughts_controller.rb
class Blog::Posts::DailyLifeController < Blog::BaseController
  before_action -> { setup_post(:thoughts) }, except: :index
  before_action -> { page_name(:post_index) }, only: :index

  def index
    @category = :thoughts
  end

  def show; end
end

app/helpers/admin/blog/posts_helper.rb
module Admin::Blog::PostsHelper
  def refined_tag_list(post)
    post.tag_list.present? ? post.tag_list.map { |tag| "##{tag}" }.to_s.delete("\"|,|[|]") : ""
  end
end

app/views/common/partials/posts/_post.html.slim
.col-sm-8.col-sm-offset-1
  .post
    - if @post.images.present?
      .post-thumbnail
        img src="#{@post.main_image_url}" alt="#{@post.title}"
    .post-header.font-alt
      h1.post-title
        = @post.title
      .post-meta
        |By&nbsp;
        a href="#"
          |Jo
        = " | #{@post.refined_date} | 3 Comments | "
        = link_to @post.category_i18n, blog_posts_prayer_requests_path
    .post-entry
      p
        = @post.body
    // image view by galleria
    -if @post.images.present?
      .row.multi-columns-row
        - @post.images.each do |img|
          .col-sm-6.col-md-3.col-lg-3
            .gallery-item
              .gallery-image
                a.gallery href="#{img.image_url}" title="Title 1"
                  img src="#{img.thumb_url}" alt="Gallery Image 1"
                  .gallery-caption
                    .gallery-icon
                      span.icon-magnifying-glass
    / -if @post.images.present?
    /   - @post.images.each do |img|
    /     .col-sm-6.col-md-3.col-lg-3
    /       .post.margin-bottom-20.float-left
    /         .post-thumnail
    /           img src="#{img.image_url}"
  .clearfix
  .comments
    h4.comment-title.font-alt
      |There are 3 comments
    .comment.clearfix
      .comment-avatar
        img src="https://s3.amazonaws.com/uifaces/faces/twitter/ryanbattles/128.jpg" alt="avatar"
      .comment-content.clearfix
        .comment-author.font-alt
          a href="#"
            |John Doe
        .comment-body
          p
            |The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The European languages are members of the same family. Their separate existence is a myth.
        .comment-meta.font-alt
          |Today, 14:55 - &nbsp;
          a href="#"
            |Reply
      .comment.clearfix
        .comment-avatar
          img src="https://s3.amazonaws.com/uifaces/faces/twitter/draganbabic/128.jpg" alt="avatar"
        .comment-content.clearfix
          .comment-author.font-alt
            a href="#"
              |Mark Stone
          .comment-body
            p
              |Europe uses the same vocabulary. The European languages are members of the same family. Their separate existence is a myth.
          .comment-meta.font-alt
            |Today, 15:34 -&nbsp;
            a href="#"
              |Reply
    .comment.clearfix
      .comment-avatar
        img src="https://s3.amazonaws.com/uifaces/faces/twitter/pixeliris/128.jpg" alt="avatar"
      .comment-content.clearfix
        .comment-author.font-alt
          a href="#"
            |Andy
        .comment-body
          p
            |The European languages are members of the same family. Their separate existence is a myth. For science, music, sport, etc, Europe uses the same vocabulary. The European languages are members of the same family. Their separate existence is a myth.
        .comment-meta.font-alt
          |Today, 14:59 -&nbsp;
          a href="#"
            |Reply
  .comment-form
    h4.comment-form-title.font-alt
      |Add your comment
    form method="post"
      .form-group
        label.sr-only for="name"
          |Name
        input.form-control#name type="text" name="name" placeholder="Name"
      .form-group
        label.sr-only for="email"
          |Name
        input.form-control#email type="text" name="email" placeholder="E-mail"
      .form-group
        textarea.form-control#comment name="comment" rows="4" placeholder="Comment"
      button.btn.btn-round.btn-d type="submit"
        |Post comment