config/routes.rb
Rails.application.routes.draw do
  devise_for :administrators
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'home#index'

  constraints subdomain: /blog/ do
    # namespace :blog, :path => '/' do
    #   get '/', to: 'home#index', as: :root
    #   resources :home, only: :index
    #   namespace :posts do
    #     resources :prayer_requests, only: [:index, :show]
    #     resources :drama_team, only: [:index, :show]
    #     resources :korean_ministry, only: [:index, :show]
    #     resources :devotion, only: [:index, :show]
    #     resources :family, only: [:index, :show]
    #     resources :daily_life, only: [:index, :show]
    #     resources :tags, only: [:create, :show]
    #   end
    # end
  end

  constraints subdomain: // do
    get '/', to: 'blog/home#index', as: :root
    resources :home
    namespace :admin do
      resources :dashboard, only: :index
      namespace :blog do
        resources :posts do
          post :posting, on: :member
          post :undo, on: :member
        end
      end
    end
    namespace :blog do
      resources :home, only: :index
      namespace :posts do
        resources :prayer_requests, only: %i[index show]
        resources :drama_team, only: %i[index show]
        resources :korean_ministry, only: %i[index show]
        resources :devotion, only: %i[index show]
        resources :family, only: %i[index show]
        resources :daily_life, only: %i[index show]
        resources :tags, only: %i[create show]
        resources :thoughts, only: %i[index show]
      end
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :blog do
      resources :home, only: :index
      resources :posts, only: %i[index show] do
        get :tags_index, on: :collection
        resources :image_sort do
          put :sort, on: :member
        end
      end
    end
  end
end

app/views/common/partials/_blog_footer.html.slim
.module-small.bg-dark
  .container
    .row
      .col-sm-3
        .widget
          h5.widget-title.font-alt
            |About Titan
          p
            |The languages only differ in their grammar, their pronunciation and their most common words.
          p
            |Phone: +1 234 567 89 10
          |Fax: +1 234 567 89 10
          p
            |Email:&nbsp;
          a href="#"
            |somecompany@example.com
      .col-sm-3
        .widget
          h5.widget-title.font-alt
            |Recent Comments
          ul.icon-list
            li
              |Maria on&nbsp;
              a href="#"
                |Designer Desk Essentials
            li
              |John on&nbsp;
              a href="#"
                |Realistic Business Card Mockup
            li
              |Andy on&nbsp;
              a href="#"
                |Eco bag Mockup
            li
              |Jack on&nbsp;
              a href="#"
                |Bottle Mockup
            li
              |Mark on&nbsp;
              a href="#"
                |Our trip to the Alps
      .col-sm-3
        .widget
          h5.widget-title.font-alt
            |Blog Categories
          ul.icon-list
            - Post.categories_i18n.invert.each do |category|
              li
                = link_to category[0], blog_posts_category_index_path(category[1])
                |&nbsp;&nbsp;
                i.fa.fa-caret-right
                = "  #{Post.posts_count category[1]}"
      .col-sm-3
        .widget
          h5.widget-title.font-alt
            |Popular Posts
          ul.widget-posts
            li.clearfix
              .widget-posts-image
                a href="#"
                  img src="/assets/rp-1.jpg" alt="Post Thumbnail"
              .widget-posts-body
                .widget-posts-title
                  a href="#"
                    |Designer Desk Essentials
                .widget-posts-meta
                  |23 january
            li.clearfix
              .widget-posts-image
                a href="#"
                  img src="/assets/rp-2.jpg" alt="Post Thumbnail"
              .widget-posts-body
                .widget-posts-title
                  a href="#"
                    |Realistic Business Card Mockup
                .widget-posts-meta
                  |15 February
hr.divider-d
footer.footer.bg-dark
  .container
    .row
      .col-sm-6
        p.copyright.font-alt
          |&copy; 2017&nbsp;
          a href="index.html"
            |TitaN
          |, All Rights Reserved
      .col-sm-6
        .footer-social-links
          a href="#"
            i.fa.fa-facebook
          a href="#"
            i.fa.fa-twitter
          a href="#"
            i.fa.fa-dribbble
          a href="#"
            i.fa.fa-skype

app/views/common/partials/_blog_header.html.slim
.page-loader
/   .loader
/     |Loading...
nav.navbar.navbar-custom.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle type="button" data-toggle="collapse" data-target="#custom-collapse"
        span.sr-only
          |Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href="#{root_path}" style="text-transform: none;"
        |HeluvsJ
    .collapse.navbar-collapse#custom-collapse
      ul.nav.navbar-nav.navbar-right
        li
          a href="#"
            |About me
        li
          a href="#"
            |About Japan
        li.dropdown
          a.dropdown-toggle href="#" data-toggle="dropdown"
            |Category
          ul.dropdown-menu
            - Post.categories_i18n.invert.each do |category|
              li
                = link_to category[0], blog_posts_category_index_path(category[1])
        li
          a href="#"
            |Contact
section.home-section.home-blog-height.home-parallax.home-fade.bg-dark-30#home data-background="/assets/section-2.jpg"
  .titan-caption
    .caption-content
      .font-alt.mb-30.titan-title-size-1
        |Hello &amp; welcome
      .font-alt.mb-40.titan-title-size-4
        |Titan is
        span.rotate
          |  Amazing | Inspiring | Stylish

app/views/common/partials/_blog_sidebar.html.slim
- enable_vue ||= false
.col-sm-4.col-md-3.sidebar ref="sidebar"
  .widget
    - if enable_vue
      .search-box
        input.form-control type="text" placeholder="Search" v-model="search_keyword"
        button.search-btn v-on:click="search_posts" v-on:keyup.enter="search_posts"
          i.fa.fa-search
  .widget
    h5.widget-title.font-alt
      |Blog Categories
    ul.icon-list
      - Post.categories_i18n.invert.each do |category|
        li
          = link_to category[0], blog_posts_category_index_path(category[1])
          |&nbsp;&nbsp;
          i.fa.fa-caret-right
          = "  #{Post.posts_count category[1]}"
  .widget
    h5.widget-title.font-alt
      |Latest Blog Posts
    ul.widget-posts
      - lastest_posts.each do |post|
        li.clearfix
          .widget-posts-image
            = link_to blog_posts_category_show_path(post, post.category) do
              img src="#{post.main_image_url}" alt="#{post.title}"
          .widget-posts-body
            .widget-posts-title
              = link_to post.truncate_title, blog_posts_category_show_path(post, post.category)
            .widget-posts-meta
              = post.refined_date
  .widget
    h5.widget-title.font-alt
      |Tag
    .tags.font-serif
      - Post.popular_tags.each do |tag|
        = link_to tag.name, blog_posts_tag_path(tag.name), rel: "tag"
  .widget
    h5.widget-title.font-alt
      |Text
    |The languages only differ in their grammar, their pronunciation and their most common words. Everyone realizes why a new common language would be desirable: one could refuse to pay expensive translators.
  .widget
    h5.widget-title.font-alt
      |Recent Comments
    ul.icon-list
      li
        |Maria on&nbsp;
        a href="#"
          |Designer Desk Essentials
      li
        |John on&nbsp;
        a href="#"
          |Realistic Business Card Mockup
      li
        |Andy on&nbsp;
        a href="#"
          |Eco bag Mockup
      li
        |Jack on&nbsp;
        a href="#"
          |Bottle Mockup
      li
        |Mark on&nbsp;
        a href="#"
          |Our trip to the Alps